import Foundation

public actor DecisionCoordinator {
    public private(set) var lastDecision:Recommendation?
    private let engine:DecisionEngine; private let recommender:RecommendationEngine; private let voice:VoiceEngine; private let diagnostics:Diagnostics; private let minimumPriority:RecommendationPriority
    public init(engine:DecisionEngine=DecisionEngine(),recommender:RecommendationEngine=RecommendationEngine(),voice:VoiceEngine=VoiceEngine(),diagnostics:Diagnostics=Diagnostics(),minimumPriority:RecommendationPriority = .medium){self.engine=engine;self.recommender=recommender;self.voice=voice;self.diagnostics=diagnostics;self.minimumPriority=minimumPriority}
    public func process(_ analysis:FrameAnalysis,groqLatencyMs:Double) async -> Recommendation? {
        let start=Date();let received=analysis.recommendation;let decided=engine.makeDecision(from:analysis) ?? received.map{Recommendation(text:$0.message,priority:$0.priority)};guard let decided else {await diagnostics.log("timestamp=\(analysis.timestamp) groq_latency_ms=\(groqLatencyMs) players=\(analysis.observedPlayersCount) ball_detected=\(analysis.ballObserved) spaces=\(analysis.freeSpacesObserved) recommendation_received=false decision=none tts_triggered=false");return nil};lastDecision=decided;guard decided.priority >= minimumPriority else {await diagnostics.log("timestamp=\(analysis.timestamp) groq_latency_ms=\(groqLatencyMs) players=\(analysis.observedPlayersCount) ball_detected=\(analysis.ballObserved) spaces=\(analysis.freeSpacesObserved) recommendation_received=true decision=\(decided.text) tts_triggered=false reason=priority");return decided};guard let accepted=await recommender.accept(decided) else {await diagnostics.log("timestamp=\(analysis.timestamp) groq_latency_ms=\(groqLatencyMs) players=\(analysis.observedPlayersCount) ball_detected=\(analysis.ballObserved) spaces=\(analysis.freeSpacesObserved) recommendation_received=true decision=\(decided.text) tts_triggered=false reason=cooldown");return decided};let audioStart=Date();voice.speak(accepted.text);let audioMs=Date().timeIntervalSince(audioStart)*1000;let decisionMs=Date().timeIntervalSince(start)*1000;await diagnostics.log("timestamp=\(analysis.timestamp) groq_latency_ms=\(groqLatencyMs) players=\(analysis.observedPlayersCount) ball_detected=\(analysis.ballObserved) spaces=\(analysis.freeSpacesObserved) recommendation_received=true decision=\(accepted.text) tts_triggered=true decision_ms=\(decisionMs) audio_ms=\(audioMs)");return accepted
    }
}
