#if os(iOS)
import SwiftUI
import UIKit

public struct DebugOverlay:View{public let analysis:FrameAnalysis?;public let recommendation:Recommendation?;public let latencyMs:Double;public let fps:Double;public init(analysis:FrameAnalysis?,recommendation:Recommendation?,latencyMs:Double=0,fps:Double=0){self.analysis=analysis;self.recommendation=recommendation;self.latencyMs=latencyMs;self.fps=fps}
 public var body:some View{GeometryReader{proxy in ZStack{if let a=analysis{ForEach(a.teammates,id:\.id){player in box(player,color:.green,label:"M")};ForEach(a.opponents,id:\.id){player in box(player,color:.red,label:"A")};if let p=a.controlledPlayer{box(p,color:.blue,label:"CONTROLADO")};if let ball=a.ball{marker(ball,color:.orange,label:"BOLA")};ForEach(Array(a.freeSpaces.enumerated()),id:\.offset){_,space in marker(space.center,color:.purple,label:"ESPAÇO")}};VStack{HStack{Text(String(format:"%.0f ms · %.1f FPS",latencyMs,fps)).font(.caption).padding(6).background(.black.opacity(0.7)).foregroundStyle(.white);Spacer()};Spacer();HStack{Text(recommendation?.text ?? "Sem recomendação").font(.headline).padding(8).background(.black.opacity(0.75)).foregroundStyle(.white);Spacer()}.padding()}}}}
 private func box(_ p:PlayerObservation,color:Color,label:String)->some View{Group{if let b=p.boundingBox{RoundedRectangle(cornerRadius:3).stroke(color,lineWidth:2).frame(width:b.width*UIScreen.main.bounds.width,height:b.height*UIScreen.main.bounds.height).overlay(Text(label).font(.caption2).background(color).foregroundStyle(.white)).position(x:(b.x+b.width/2)*UIScreen.main.bounds.width,y:(b.y+b.height/2)*UIScreen.main.bounds.height)}else{marker(p.position,color:color,label:label)}}}
 private func marker(_ p:Point2D,color:Color,label:String)->some View{Text(label).font(.caption2).padding(3).background(color).foregroundStyle(.white).clipShape(RoundedRectangle(cornerRadius:3)).position(x:p.x*UIScreen.main.bounds.width,y:p.y*UIScreen.main.bounds.height)} }
#endif
